spring.application.name=ibuild-stock


#=======================================Conection DB=======================================#
spring.datasource.url=jdbc:postgresql://localhost:5432/stock
spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.dbcp2.pool-prepared-statements=true
spring.datasource.dbcp2.max-open-prepared-statements=450